//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfBizService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfBizService")]
    public partial class LoginInfo : object
    {
        
        private string credentialField;
        
        private string userIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string credential
        {
            get
            {
                return this.credentialField;
            }
            set
            {
                this.credentialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserModel", Namespace="http://schemas.datacontract.org/2004/07/WcfBizService")]
    public partial class UserModel : object
    {
        
        private System.Guid authGuidField;
        
        private string emailField;
        
        private string mimaField;
        
        private string rolesField;
        
        private string userIdField;
        
        private string userNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid authGuid
        {
            get
            {
                return this.authGuidField;
            }
            set
            {
                this.authGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mima
        {
            get
            {
                return this.mimaField;
            }
            set
            {
                this.mimaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string roles
        {
            get
            {
                return this.rolesField;
            }
            set
            {
                this.rolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfBizService.IAccountSvc")]
    public interface IAccountSvc
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountSvc/Echo", ReplyAction="http://tempuri.org/IAccountSvc/EchoResponse")]
        string Echo(int knock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountSvc/Echo", ReplyAction="http://tempuri.org/IAccountSvc/EchoResponse")]
        System.Threading.Tasks.Task<string> EchoAsync(int knock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountSvc/AuthenticateUser", ReplyAction="http://tempuri.org/IAccountSvc/AuthenticateUserResponse")]
        WcfBizService.UserModel AuthenticateUser(WcfBizService.LoginInfo login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountSvc/AuthenticateUser", ReplyAction="http://tempuri.org/IAccountSvc/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<WcfBizService.UserModel> AuthenticateUserAsync(WcfBizService.LoginInfo login);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IAccountSvcChannel : WcfBizService.IAccountSvc, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AccountSvcClient : System.ServiceModel.ClientBase<WcfBizService.IAccountSvc>, WcfBizService.IAccountSvc
    {
        
        /// <summary>
        /// 實作此部分方法來設定服務端點。
        /// </summary>
        /// <param name="serviceEndpoint">要設定的端點</param>
        /// <param name="clientCredentials">用戶端認證</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AccountSvcClient() : 
                base(AccountSvcClient.GetDefaultBinding(), AccountSvcClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAccountSvc.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountSvcClient(EndpointConfiguration endpointConfiguration) : 
                base(AccountSvcClient.GetBindingForEndpoint(endpointConfiguration), AccountSvcClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountSvcClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AccountSvcClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountSvcClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AccountSvcClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string Echo(int knock)
        {
            return base.Channel.Echo(knock);
        }
        
        public System.Threading.Tasks.Task<string> EchoAsync(int knock)
        {
            return base.Channel.EchoAsync(knock);
        }
        
        public WcfBizService.UserModel AuthenticateUser(WcfBizService.LoginInfo login)
        {
            return base.Channel.AuthenticateUser(login);
        }
        
        public System.Threading.Tasks.Task<WcfBizService.UserModel> AuthenticateUserAsync(WcfBizService.LoginInfo login)
        {
            return base.Channel.AuthenticateUserAsync(login);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAccountSvc))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAccountSvc))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:9311/AccountSvc.svc");
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AccountSvcClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAccountSvc);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AccountSvcClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAccountSvc);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAccountSvc,
        }
    }
}
